server:
  port: 85630

com:
  delete-file:
      number: 30
      datePattern: yyyyMMddHHmmss
      suffix: zip
      cron: 0 0/10 * * * ?

      sourcePath: C:\\Users\\WorkStation\\Documents\\My Games\\FINAL FANTASY VII REMAKE
      tempPath: F:\\游戏存档\\最终幻想7-重置版
      remotePath: O:\\360云盘文件\\游戏存档\\最终幻想7-重置版
      fileName: 最终幻想7-重置版


