server:
  port: 85630

com:
  delete-file:
    sourcePath: C:\\Users\\WorkStation\\Documents\\My Games\\FINAL FANTASY VII REMAKE
    remotePath: O:\\360云盘文件\\游戏存档\\最终幻想7-重置版
    suffix: zip
    fileName: 最终幻想7-重置版
    cron: 0 0/10 * * * ?
